export enum MAZE_NAMES {
  SET_PLAYER_POSITION = "SET_PLAYER_POSITION",
  SET_STEPS = "SET_STEPS",
  SET_WINNING = "SET_WINNING",
  SET_GAME_START = "SET_GAME_START",
  SET_RESTART_GAME = "SET_RESTART_GAME",
}
