const mazes = [
  [
    { type: "wall" },
    { type: "entrance" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
  ],
  [
    { type: "wall" },
    { type: "path" },
    { type: "wall" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "wall" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "wall" },
  ],
  [
    { type: "wall" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "wall" },
    { type: "path" },
    { type: "wall" },
    { type: "path" },
    { type: "wall" },
    { type: "path" },
    { type: "wall" },
    { type: "wall" },
  ],
  [
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "wall" },
    { type: "path" },
    { type: "path" },
    { type: "wall" },
  ],
  [
    { type: "wall" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "path" },
    { type: "wall" },
  ],
  [
    { type: "wall" },
    { type: "path" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "wall" },
  ],
  [
    { type: "wall" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "wall" },
    { type: "path" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
  ],
  [
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "path" },
    { type: "wall" },
    { type: "path" },
    { type: "wall" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "wall" },
  ],
  [
    { type: "wall" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "wall" },
    { type: "path" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
  ],
  [
    { type: "wall" },
    { type: "wall" },
    { type: "path" },
    { type: "wall" },
    { type: "wall" },
    { type: "path" },
    { type: "wall" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "wall" },
    { type: "wall" },
  ],
  [
    { type: "wall" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "wall" },
    { type: "path" },
    { type: "path" },
    { type: "path" },
    { type: "wall" },
    { type: "path" },
    { type: "path" },
    { type: "exit" },
  ],
  [
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
    { type: "wall" },
  ],
];

export default mazes;
